### ISSUE TITLE
Softstart not working

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#10]
I updated to latest git and it seems that softstart is not working anymore. When i switch channel or jump in movie the picture stands still for ~1 second insdead of playing slower until in sync with audio.

I use VDPAU and an GT630 (GK208)
Updated from 3dac1fe2eefe96828c3fc4ce8c9061cd6c01d33a

**Comment by ua0lnj** [comment]
Yes, I made it to sync faster. Did this affect the sync?
Or was it better?

**Comment by MegaV0lt** [comment]
Can not say right now. Have to watch it for some time.

**Comment by MegaV0lt** [comment]
Not working. I get audio out of sync; even when i activate driftcorrection ... Issue is on sd and hd channels

**Comment by ua0lnj** [comment]
Ok, understood. But comit 3dac1fe for cuvid, not for vdpau. It looks like another commit has affected.
I will try to change the sync.

**Comment by MegaV0lt** [comment]
I am not sure if it was also before, because i ust it sinc a few weeks...

**Comment by ua0lnj** [comment]
Should be fixed.

**Comment by MegaV0lt** [comment]
Thanks for reenabling
