### ISSUE TITLE
Stuttering audio

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#11]
I use VDPAU and an GT630 (GK208)

sometimes i get stuttering audio (AC-3). it sounds a little bit like it all is under water. Nothing in log. After switching to another channel and back it is gone. 
seen on 'n-tv HD' at astra 19,2°

**Comment by MegaV0lt** [comment]
In my distri thith is the default shd:
https://github.com/lucianm/softhddevice-unified

I can not remember that i had audio problems there.

**Comment by ua0lnj** [comment]
Try now.

**Comment by MegaV0lt** [comment]
Now after pause the audio is on for a second, then muted, on, muted... and so on.
Also after jumping around in Video.

Unusable in this state

**Comment by ua0lnj** [comment]
Pause in live or play record?
ac3 or stereo too?
I have not this trouble, give more info, logs.
May be give me you record for test.

**Comment by ua0lnj** [comment]
Try comment 3 lines and test.
https://github.com/ua0lnj/vdr-plugin-softhddevice/blob/vdpau%2Bvaapi%2Bcuvid/video.c#L10706-L10708

**Comment by MegaV0lt** [comment]
When playing a recording. In my case "nano" / 3sat @ Astra 19,2°E
Audio is AC3 and HD Resolution (1280*720)

I am back now on my distris shd. That works without issues

**Comment by MegaV0lt** [comment]
Here is a testrecording of the tvstation ~4 Minutes/200MB
https://www.dropbox.com/s/awco6tnnmwklj1b/%40Steffens_entdeckt%233A_Patagonien_Raues_Ende_der_Welt.tar.xz?dl=0

**Comment by ua0lnj** [comment]
Yes, have your issue.
Will watch.

**Comment by ua0lnj** [comment]
Fixed.
