### ISSUE TITLE
Audi out of sync after pause

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#12]
I use VDPAU and an GT630 (GK208)

After Pausing and resuming video the audi is out of sync on recordings (1920*1080) and possible others.
Jumping forward and backwards solves the dely temporarly

**Comment by ua0lnj** [comment]
Wait for the next commit, I'm doing sync.

**Comment by ua0lnj** [comment]
Fixed.

**Comment by MegaV0lt** [comment]
Is gotten worse. after pause the vide syncs very long and audio  stops and resyncs...

**Comment by ua0lnj** [comment]
Give me you records please.

**Comment by ua0lnj** [comment]
Fixed.
