### ISSUE TITLE
video is only drawn to the lower half of the screen when tuning certain channels

### ISSUE THREAD

**Issue by seahawk1986** [ua0lnj/vdr-plugin-softhddevice#13]
Hello,
I discovered an odd behavior when tuning a certain DVB-C HD channel if the output resolution of the display resp. TV is less than 1920x1080 (e.g. 1280x720): the OSD and video image is drawn to the lower half of the screen with a big black rectangle above (and it keeps that way until I detach and reattach softhddevice, changing channels alone does not help). Here is a link to a short recording of this channel which should be able to cause the issue: https://drive.google.com/open?id=1zsY31j4TDWEs1Ak7uP3r6IrlOX4kICqE

I have been told that the Channel "Bibel TV HD" on Astra 19.2 causes a similar problem (which might be easier for testing if one has a DVB-S2 card):
````
Bibel TV HD;ORS:11243:HC56M2S0:S19.2E:22000:2240=27:2241=deu@3:2245:0:13224:1:1003:0
````

**Comment by ua0lnj** [comment]
Will watch.
I can't receive 19.2, so use recordings.

**Comment by ua0lnj** [comment]
Found what the problem is, i'll do it tomorrow.

**Comment by ua0lnj** [comment]
Fixed.
