### ISSUE TITLE
crashes if subtitles are enabled

### ISSUE THREAD

**Issue by tjaalton** [ua0lnj/vdr-plugin-softhddevice#15]
I've installed latest yavdr which uses a snapshot of this plugin, and if I enable DVB subtitles, VDR crashes in seconds, and keeps crashing until the setting is reset.

**Comment by tjaalton** [comment]
using nvidia 340 on
03:00.0 VGA compatible controller: NVIDIA Corporation GT218 [ION] (rev a2)

**Comment by ua0lnj** [comment]
Does this happen on a channel with subtitles, or on any channel?
You need to enable debug mode and download the log, as well as publish a record with subtitles if a problem occurs on the channel with subtitles.

**Comment by tjaalton** [comment]
Only on channels with (DVB) subtitles, here's a snippet of the log

Mar 29 10:21:17 vdr vdr: [1683] switching to channel 7 T-8438-4865-25 (Yle Teema & Fem HD)
Mar 29 10:21:18 vdr vdr: [2757] device 1 TS buffer thread ended (pid=1683, tid=2757)
Mar 29 10:21:18 vdr vdr: [2756] buffer stats: 29516 (0%) used
Mar 29 10:21:18 vdr vdr: [2756] device 1 receiver thread ended (pid=1683, tid=2756)
Mar 29 10:21:18 vdr vdr: [2760] device 1 receiver thread started (pid=1683, tid=2760, prio=high)
Mar 29 10:21:18 vdr vdr: [2761] device 1 TS buffer thread started (pid=1683, tid=2761, prio=high)
Mar 29 10:21:19 vdr vdr: audio/alsa: using device 'default'
Mar 29 10:21:19 vdr vdr: audio/alsa: start delay 336ms
Mar 29 10:21:19 vdr vdr: video: get hwaccel context, not supported
Mar 29 10:21:20 vdr vdr: audio/alsa: avail underrun error? 'Katkennut putki'
Mar 29 10:21:20 vdr vdr: video/vdpau: synced after 50 frames
Mar 29 10:21:27 vdr vdr: [2763] subtitle converter thread started (pid=1683, tid=2763, prio=high)
Mar 29 10:21:27 vdr kernel: [ 4804.984380] oglThread[1744]: segfault at 8 ip 00007fda5511b105 sp 00007fda077fdd60 error 4 in libvdr-softhddevice.so.2.4.1[7fda550e7000+3c000]
Mar 29 10:21:27 vdr kernel: [ 4804.984402] Code: 00 66 0f 62 ca 48 83 c0 10 39 ce 66 0f 6c c1 48 89 07 0f 95 c0 44 39 c2 0f 95 c2 0f 11 47 14 09 d0 88 47 24 c3 f3 0f 1e fa 53 <80> 7f 08 00 48 89 fb 75 06 48 8b 07 ff 50 10 8b 4b 18 8b 53 14 31

I'll try to record a short clip with subs.

**Comment by tjaalton** [comment]
I've put the recording (6MB) here:
https://aaltoset.kapsi.fi/vdr/dvb-rec.tar

starting the playback will immediately crash vdr here

**Comment by ua0lnj** [comment]
I reproduced crash, will watch.
