### ISSUE TITLE
black screen issue

### ISSUE THREAD

**Issue by 9000h** [ua0lnj/vdr-plugin-softhddevice#16]
there is another maybe new issue, if you go to the menu and select "softhddevice" and then go back (hit Enter) to the current running channel the video will stop with a black screen.

**Comment by ua0lnj** [comment]
Not reproducible.
The sequence of actions is not clear.
You use RCU or keyboard for vdr control?
Why for back command you use enter?

**Comment by 9000h** [comment]
it's keyboard, and the behaviour probably normal
