### ISSUE TITLE
SD unusable. Live and recordings

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#17]
Audio is ok, but video disorted. Sample recording 720*576 (51 MB):
https://www.dropbox.com/s/ektsxxirb3p815z/%40News_Spezial%233A_Die_Corona-Krise.tar.xz?dl=1

**Comment by 9000h** [comment]
n-tv SD from Astra 19.2 is playing fine here with VAAPI

**Comment by MegaV0lt** [comment]
VDPAU not

**Comment by ua0lnj** [comment]
Your recording is playing fine with me.
Did it appear exactly after the last commit?
Have you any errors in log?

**Comment by ua0lnj** [comment]
Try the last commit, maybe everything is fine.

**Comment by MegaV0lt** [comment]
Yes the last commit. Nothing in the log. Sorry

**Comment by MegaV0lt** [comment]
Just installed the latest version. No change in behavior. SD not usable.
Made a small video with my mobile:
https://darkwing.ddns.net/nextcloud/index.php/s/aNErDFjdSftcGtN (24MB)

**Comment by seahawk1986** [comment]
I have the same problem on Ubuntu 18.04 with ffmpeg 3.4. It worked up to commit 2da287e.

Using Ubuntu 20.04 with ffmpeg 4.2.x I can't reproduce this issue.

**Comment by ua0lnj** [comment]
Very interesting, thanks seahawk1986.
Will treat.

**Comment by ua0lnj** [comment]
Problem for vdpau mpeg2 format select, tommorow will be done.

**Comment by ua0lnj** [comment]
Fixed.

**Comment by MegaV0lt** [comment]
Test it tomorrow

**Comment by MegaV0lt** [comment]
Is working again. Thanks.
