### ISSUE TITLE
OSD issue

### ISSUE THREAD

**Issue by 9000h** [ua0lnj/vdr-plugin-softhddevice#18]
if you resize from fullscreen to windowed mode the osd get messed up
![Screenshot from 2020-05-05 18-05-57](https://user-images.githubusercontent.com/3009073/81088486-4859c680-8efb-11ea-9d86-4952cc05e85b.png)

**Comment by ua0lnj** [comment]
Va-api?

**Comment by 9000h** [comment]
Yes

**Comment by ua0lnj** [comment]
Fixed [https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/92c6d618ae10810a511ccc088e9fde8ef26a931c](url)

**Comment by 9000h** [comment]
great !
![Screenshot from 2020-05-07 15-42-11](https://user-images.githubusercontent.com/3009073/81301500-6cdbad00-9079-11ea-8b21-e06a5bebb37e.png)
