### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#19]
Can not build under gentoo
https://www.dropbox.com/s/i8tbw2xqa5z9chh/make_shd.log?dl=0

> In file included from softhddevice.cpp:51:0:
> codec.h: Im globalen Gültigkeitsbereich:
> codec.h:62:6: Fehler: »AVCodec« bezeichnet keinen Typ
>       AVCodec *VideoCodec;                ///< video codec
>       ^~~~~~~
and so on

**Comment by ua0lnj** [comment]
Try in softhddevice.cpp line 47 uncomment
#include <libavcodec/avcodec.h>

**Comment by MegaV0lt** [comment]
Not working. See log 
https://www.dropbox.com/s/3sg0jqid6hx9okp/make_shd.log?dl=0

**Comment by MegaV0lt** [comment]
When i also uncomment line 49 (audio.h) it compiles

**Comment by ua0lnj** [comment]
Ok, hard to remove compiler warnings...

**Comment by ua0lnj** [comment]
Fixed https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/856fb47911fb4b397b2ecc8dc944a4b3cb25aeb6
