### ISSUE TITLE
double call to function

### ISSUE THREAD

**Issue by 9000h** [ua0lnj/vdr-plugin-softhddevice#2]
is this by purpose
https://github.com/ua0lnj/vdr-plugin-softhddevice/blob/3989b14982d023c79c42929c97348e49f25bbb12/video.c#L5781-L5782

**Comment by ua0lnj** [comment]
It migrated from [https://github.com/louisbraun/softhddevice-openglosd/blob/569fde5dce6750eabcd889d07b3298d5764fce34/video.c#L4390](url)
I will test without double on AMD some time later.
Test on Intel, if you want.

**Comment by 9000h** [comment]
on Intel I could not see any difference

**Comment by ua0lnj** [comment]
On AMD vaapi I could not see any difference too, but I think this code need for soft deinterlace. 
Until I touch this code, until there is more specific information.
