### ISSUE TITLE
[1080/1088] Picture defect at bottom on some channels

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#24]
Picture defect at bottom on some channels.

Same Bug as described here: https://www.vdr-portal.de/forum/index.php?thread/133364-softhddevice-bildfehler-am-unteren-rand/&postID=1322733#post1322733

Bug reapeared.

**Comment by ua0lnj** [comment]
Yes...

**Comment by MegaV0lt** [comment]
Works now as expected. Thanks
