### ISSUE TITLE
Grab with cuvid - vdr segfaults

### ISSUE THREAD

**Issue by schoebelh** [ua0lnj/vdr-plugin-softhddevice#27]
I try to run your plugin with "-v cuvid" and want to use the boblight plugin. When vdr starts it segfaults instantly:

Oct 20 12:14:52 yavdr kernel: [  592.325753] softhddev video[22365]: segfault at 10 ip 00007f5a2dfacc78 sp 00007f5a20ff8db0 error 4 in libGLX.so.0.0.0[7f5a2dfab000+1b000]
Oct 20 12:14:52 yavdr kernel: [  592.325760] Code: ff 83 cf ff e8 c9 e7 ff ff 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 41 56 41 89 ce 41 55 49 89 d5 41 54 49 89 f4 55 48 89 fd 53 <8b> 76 10 e8 e0 59 00 00 48 85 c0 74 43 4c 89 e6 48 89 c3 4c 89 ea
Oct 20 12:14:52 yavdr systemd[1]: vdr.service: Main process exited, code=killed, status=11/SEGV

System is Ubuntu Focal (yavdr ansible).

How can i help to find the problem?

...Hagen

**Comment by ua0lnj** [comment]
Please give me the entire log of vdr.
It's work without boblight plugin?

**Comment by ua0lnj** [comment]
I looked at the boblight plugin code and it seems I was able to reproduce the problem, I will solve it.

**Comment by ua0lnj** [comment]
Should be fixed in https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/40ab4158bd931dad37c2e9ee2db4585c921637c0
