### ISSUE TITLE
va-api: returning from plugin setup menu damage current LiveTV/recording-view color map

### ISSUE THREAD

**Issue by pbiering** [ua0lnj/vdr-plugin-softhddevice#34]
even using latest version from branch "vdpau+vaapi+cuvid" something is very strange. Once checking plugin setup even in case nothing is changed, returning from plugin setup with "back" changes display of LiveTV/recording-view by damaging somehow the color map. It returns to normal after a change: LiveTV -> recording-view or vice-versa.

Using "va-api" with Intel Broxton (Gen9)

Tried serveral plugin options, didn't found one which is preventing that issue.

Looks like something happen during returning from plugin setup related to current graphics output, which is reseted back to normal once a new video stream is displayed.

BTW: OSD colors stay ok even if LiveTV/recording-view color map is damaged.

If required I can supply a short movie.

**Comment by ua0lnj** [comment]
Try setting the brightness and contrast to 10 for vaapi in the menu and see the result. There is such a problem for vaapi if the default settings are used, due to the difference between the settings for vdpau and cuvid.

**Comment by pbiering** [comment]
Thank you for the hint, this improves the situation a lot
Before: brightness=0 contrast=100 saturation=100  (but looks like not honored during VDR start)
Now: brightness=0, contrast=10, saturiation=10 (mentioned defaults) -> all fine even after exit from plugin
