### ISSUE TITLE
softhddevice+vdr-mpv geometry problem with some desktop managers

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-softhddevice#35]
Hi Andrey I've encountered an annoying issue with kde and my favorite desktop deepin. I'm using them on manjaro. With gnome,mate and cinnamon all is ok starting these plugins  with vdr -P"softhddevice -v cuvid -f -g 1920x1080+1920+0 -w disable-ogl-osd"  -P"mpv -v gpu -h cuda -a alsa -g 1920x1080+1920+0".
To have vdr in fullscreen on my secondary screen  I have to start softhddevice with 1919x1080 in kde and with 1600x900 in deepin (if I use 1920x1080 vdr start on my primary screen I don't know why). With this workaround all seem working: I have vdr (softhddevice) on my secondary screen. then I play a video and I have vdr-mpv correctly working on my secondary screen. But the problem happens when I stop the vdr-mpv video because  vdr (softhddevice) go on my primary monitor. Then if I play a video with vdr-mpv from my primary screen the video go correctly on my secondary monitor.
So the problem is that stopping vdr-mpv in my secondary screen "move" softhddevice on my primary screen.
This geometry problem happen only starting in fullscreen and it seems to me that vdr-plugin-mpv geometry is working perfectly. The geometry problem seem only related to softhddevice  but it appears clear stopping vdr-mpv video. 
I have the same behavior on both desktops. Maybe I've used too many words....I hope you can fix this annoying issue too.

**Comment by ua0lnj** [comment]
For interest, why -w disable-ogl-osd?

**Comment by nikjsu** [comment]
Good question....I think I've used it before discover the cuvid driver maybe to map my remote. I've tried just now and I can confirm that with cuvid it isn't necessary.

**Comment by nikjsu** [comment]
I've made many tests. Now I can answer better to your last question. There were a reason. I've tested many desktop managers this month using the same runvdr script because deepin was broken in manjaro.  On Kde and Deepin (both share kwin) without the -w disable-ogl-osd the vdr starts without osd  and without lirc. If I restart repeatedly vdr, I can obtain some sessions with osd loaded but the solution at the moment is using that workaround. Today I've made many tests with gnome kde and deepin using the same system so the same kernel and same nvidia proprietary drivers. I'm sure gnome and probably other desktops doesnt need that workaround but kde and Deepin can load the osd correctly but only using -w disable-ogl-osd.

**Comment by ua0lnj** [comment]
There is such a problem with the VDPAU, but it should not be with the CUVID...

**Comment by ua0lnj** [comment]
Try this patches, one at a time, not at the same time.
[shd-1.patch.gz](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/5861717/shd-1.patch.gz)
[shd-2.patch.gz](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/5861719/shd-2.patch.gz)
[shd-3.patch.gz](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/5861720/shd-3.patch.gz)

**Comment by nikjsu** [comment]
No luck with these patches. Anyway I've made some google search and I've discovered that this problem is due to a kde bug. I've read about problems with kodi too and I've tested  kodi and found  the same problem and xineliboutput too have problems with kde... Luckly I've discovered that there is a solution using kde window rules: https://askubuntu.com/questions/1078160/specifying-the-active-screen-for-fullscreen-kde-applications. I've tested on kde and deepin and this way works perfectly. For what I've noticed your geometry implementation is working better than kodi and xineliboutput seen that without mpv the geometry is honored. At this point seen that this is a kde bug and seen I've found a kde internal solution maybe is better to use your time to solve other tasks. You can close this ticket. Thanks for your efforts

**Comment by ua0lnj** [comment]
I tested with KDE on Fedora 33, and geometry works fine. Maybe this fixed it there.
