### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by fiveten59** [ua0lnj/vdr-plugin-softhddevice#36]
Attached Italian translation
Bye
[it_IT.po.tar.gz](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/5897656/it_IT.po.tar.gz)

**Comment by ua0lnj** [comment]
Added.
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/dbf519dd59d0cad243838975833e2b241901a209
