### ISSUE TITLE
wrong OSD colors osdteletext plugin

### ISSUE THREAD

**Issue by 9000h** [ua0lnj/vdr-plugin-softhddevice#38]
Hi,
softhdcuvid(vaapi) i965 driver did it right
![Screenshot from 2021-04-21 23-18-35](https://user-images.githubusercontent.com/3009073/115622663-7137bf00-a2f8-11eb-869c-768df0427922.png)
but softhddevice vaapi i965 driver shows it wrong
![Screenshot from 2021-04-21 23-17-23](https://user-images.githubusercontent.com/3009073/115622733-87de1600-a2f8-11eb-87c4-984539fb3924.png)

vdr-plugin-osdteletext latest git and vdr-2.5.2
CU
9000h

**Comment by ua0lnj** [comment]
Ok, I'll look it.

**Comment by ua0lnj** [comment]
What git you use?
https://github.com/vdr-projects/vdr-plugin-osdteletext
https://github.com/pbiering/vdr-plugin-osdteletext
master branch?
I can't reproduce yet.

Give me please you vdr/vtx files.

**Comment by 9000h** [comment]
The first link and the master

**Comment by 9000h** [comment]
and no openglosd
Apr 25 23:11:26 localhost vdr: [55438] [softhddev]No hw driver or OpenGL Osd disabled - use soft OSD
found it
it's only happen when in the osdteletext plugin the 16 color mode is on, strange

**Comment by ua0lnj** [comment]
I'll see, with nvidia and 16 colors, the picture is generally gray.

**Comment by ua0lnj** [comment]
I found the difference.
4bpp (16 colours) works with openGL OSD only. Softhdcuvid(vaapi, drm) use it. But softhddevice with vaapi does not use it, and if you disable openGL OSD with cuvid or vdpau, you will get the same result.
It remains to understand whether need to do this color mode or not.

**Comment by ua0lnj** [comment]
Works with va-api-glx or va-api-egl and test branch, I think do not need for va-api.
