### ISSUE TITLE
Many warnings when build softhddevice 

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#4]
When i build softhddevice on my Gen2VDR i got a lot of warnings. 
See Log: https://www.dropbox.com/s/i8tbw2xqa5z9chh/make_shd.log

However it builds successful so it is not really a bug ;-)

**Comment by ua0lnj** [comment]
Someday I will do it, but now I devote all my free time to development.

**Comment by ua0lnj** [comment]
[https://github.com/ua0lnj/vdr-plugin-softhddevice/issues/8](url)

**Comment by ua0lnj** [comment]
Done https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/5255641e35f01a525f34df1be9c311b3b0be7b45

**Comment by MegaV0lt** [comment]
Thank you. Much better. One warning left

```
*** Plugin softhddevice:
WARNING, you have libavresample and libswresample together!!!
WARNING, you have libavresample and libswresample together!!!
CXX softhddevice.o
CC softhddev.o
CC video.o
CC audio.o
CC codec.o
codec.c: In Funktion »CodecVideoOpen«:
codec.c:532:36: Warnung: Klammern um Arithmetik in Operand von »|« empfohlen [-Wparentheses]
     if ((video_codec->capabilities & AV_CODEC_CAP_HWACCEL_VDPAU | CODEC_CAP_HWACCEL) &&
                                    ^
CC ringbuffer.o
GT po/softhddevice.pot
PO po/de_DE.po
MO po/de_DE.mo
LD libvdr-softhddevice.so
```

**Comment by ua0lnj** [comment]
Oh, old ffmpeg, yes.

**Comment by ua0lnj** [comment]
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/7717dd7e7d6a4b9aee721754746a0908ed72807c
