### ISSUE TITLE
Audio/Alsa warning floods syslog

### ISSUE THREAD

**Issue by frosch01** [ua0lnj/vdr-plugin-softhddevice#41]
Hi Andrey,

thx a lot for your great maintenance and enhancement work of this plugin. I had a running yavdr setup since 2016, so was no longer following the mainstream. Now, catching up again after ~6 years, I see a lot of progress, super fast channel switching and much better overlay on Intel/VAAPI. 

But I have also to say that finding this repo as the "latest" was a hard task. Perhaps you can try to update this [page](http://www.vdr-wiki.de/wiki/index.php/Softhddevice-plugin) and at least mention that this repo is available. I may help doing this, just let me know.

## My setup 

I am using the PC also as a secondary workplace running a Kubuntu desktop. There, pulseaudio is the default sound system. When I run softhddevice plugin as is, the syslog is filled massively with the message ""audio/alsa: broken driver state". It is found in audio.c:815. In various forums, people suggest to enable the AudioAlsaDriverBroken workaround which imho is no real workaround as it just suppresses the warnings being sent.

## My observations

I was instrumenting a bit and found that the PA libasound wrapper seems to behave different w.r.t. timing behavior than original libasound. At the end, the usleep made trick and not really calling snd_pcm_start(). Other measures on the call tree down to the final loop are also not effective. At the end, AlsaPlayRingbuffer() is just called again after waiting/breaking the loop in audio.c:832, 

## My patch

I added a retry handling in case there are is no buffer space available. Can you please check my commit on this [repo](https://github.com/frosch01/vdr-plugin-softhddevice/commit/9d3e12858dd97f5c3c58253e20f3134fc3764232). 

If you think the changes are fine, I suggest that you just merge/cherry-pick the change into your repo. I was not able to raise a PR against your repo as I am using an own copy (with some private changes I rely on). Github unfortunately does not support changing the "base repo" or to send PRs to any other repo than the base repo. If you feel I should do anyway, let me know and I get things done.

## Missing ALSA testing

If you have a pure ALSA setup running, I would like to ask you to check if there is any negative impact on non PA based sound. I am not able to do this currently. But I fear the difference occurs only when there is a broken device. If you prefer, I may try to detect whether PA is in use and to enable retry handling only when there is really PA sound. 

Ralph

**Comment by ua0lnj** [comment]
Ok, I'll take a look.

**Comment by ua0lnj** [comment]
I checked it on pure ALSA, everything seems to be working fine.
I'll check with pulseaudio soon.

**Comment by ua0lnj** [comment]
Added https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/89cf5d422171013fb51f2b00cb37d6fcfee58558
