### ISSUE TITLE
Screensaver

### ISSUE THREAD

**Issue by fiveten59** [ua0lnj/vdr-plugin-softhddevice#45]
At first a great thanks to your job
Thanks to test branch I finally can use the plugin on my intel hardware too
But let's come to the issue
the prob is the screensaver 
Usually during the day i listen iptv radio through Vdr  turning off the tv but after 5 minutes turning on the same tv I have blank screen with no response at all (mouse - keyboard - IR) 
Changed screensaverr to 0 in Makefile but nothing change
Yours

**Comment by ua0lnj** [comment]
Softhddevice should block the screensaver, but I really did not check it. I will test it today later.

**Comment by ua0lnj** [comment]
Also, check please if the X server is turned off after the monitor is turned off.

Try add in xorg.conf

Section "Extensions"
        Option "DPMS" "Disable"
EndSection

**Comment by fiveten59** [comment]
Nothing change adding the above lines in xorg.conf
Some more details
I get blank screen only when i turn off the monitor with vdr running on window of the os ((ubu - bullseye is the same) 
Instead with vdr running in background in another window turning on again the monitor all is okay

**Comment by ua0lnj** [comment]
What video card you use?
I tried to reproduce the problem, so far everything is working fine. I tried to run softhddevice on the second screen (TV), turned it off, waited for the screensaver, but there was no problem.I tried cuvid and vdpau on nvidia GT-1030 graphics card.
Also, please compile with enabling debug "CONFIG += -DDEBUG" in Makefile and post log.
And please describe step by step how I can reproduce the problem.

**Comment by fiveten59** [comment]
Video graphic card is the same

This the watching (listen to) a radio stream via Iptv+Radio plugin
After 30 sec (turning off the monitor) i can listen to the music but turning on blank screen
`[00007fbd60000c80] main input debug: Stream buffering done (1018 ms in 53 ms)
[00007fbd60000c80] main input debug: Decoder wait done in 0 ms
[00007fbd5c001d10] main encoder debug: looking for encoder module matching "any": 22 candidates
[00007fbd5c001d10] main encoder debug: using encoder module "twolame"
[00007fbd64006fe0] main stream out debug: input 's16l' 44100 Hz Stereo frame=1 samples/4 bytes
[00007fbd64006fe0] main stream out debug: conversion: 's16l'->'s16l' 44100 Hz->44100 Hz Stereo->Stereo
[00007fbd64006fe0] main stream out debug: conversion pipeline complete
[00007fbd5c025800] main audio resampler debug: looking for audio resampler module matching "any": 4 candidates
[00007fbd5c025800] main audio resampler debug: using audio resampler module "ugly"
[00007fbd64004190] main mux debug: adding a new input
[00007fbd64004190] mux_ts mux debug: adding input codec=mpga pid=128
[00007fbd64004190] mux_ts mux debug: new PCR PID is 128
ratio: 16:9 58880:33129`
Pls note that watchin a tv channel turning off the monitor for 30 sec i have no sound and no video and turning on blank screen and  no prob in the log 

this evening i'll try again using the other pc with intel graphic card

**Comment by fiveten59** [comment]
I forgot that it happens only with vdr on fullscreen if windowed no prob at all

**Comment by ua0lnj** [comment]
Post softhddevice section of setup.conf please.
So far I found that blocking the screensaver does not work for me.
You use 2 monitors connected to video card, or one?

**Comment by fiveten59** [comment]
Only one
It's all okay the with intel graphic card pc (the other pc)

this is setup (it's the same on all pc's)
`softhddevice.1080i.CutLeftRight = 0
softhddevice.1080i.CutTopBottom = 0
softhddevice.1080i.Deinterlace = 0
softhddevice.1080i.Denoise = 0
softhddevice.1080i.FirstField = 0
softhddevice.1080i.InverseTelecine = 0
softhddevice.1080i.Scaling = 0
softhddevice.1080i.SecondField = 0
softhddevice.1080i.Sharpen = 0
softhddevice.1080i.SkipChromaDeinterlace = 0
softhddevice.1080i_fake.CutLeftRight = 0
softhddevice.1080i_fake.CutTopBottom = 0
softhddevice.1080i_fake.Deinterlace = 0
softhddevice.1080i_fake.Denoise = 0
softhddevice.1080i_fake.FirstField = 0
softhddevice.1080i_fake.InverseTelecine = 0
softhddevice.1080i_fake.Scaling = 0
softhddevice.1080i_fake.SecondField = 0
softhddevice.1080i_fake.Sharpen = 0
softhddevice.1080i_fake.SkipChromaDeinterlace = 0
softhddevice.576i.CutLeftRight = 0
softhddevice.576i.CutTopBottom = 0
softhddevice.576i.Deinterlace = 0
softhddevice.576i.Denoise = 0
softhddevice.576i.FirstField = 0
softhddevice.576i.InverseTelecine = 0
softhddevice.576i.Scaling = 0
softhddevice.576i.SecondField = 0
softhddevice.576i.Sharpen = 0
softhddevice.576i.SkipChromaDeinterlace = 0
softhddevice.60HzMode = 0
softhddevice.720p.CutLeftRight = 0
softhddevice.720p.CutTopBottom = 0
softhddevice.720p.Deinterlace = 0
softhddevice.720p.Denoise = 0
softhddevice.720p.FirstField = 0
softhddevice.720p.InverseTelecine = 0
softhddevice.720p.Scaling = 0
softhddevice.720p.SecondField = 0
softhddevice.720p.Sharpen = 0
softhddevice.720p.SkipChromaDeinterlace = 0
softhddevice.AudioAutoAES = 0
softhddevice.AudioBufferTime = 0
softhddevice.AudioCompression = 0
softhddevice.AudioDelay = 0
softhddevice.AudioDownmix = 0
softhddevice.AudioDrift = 0
softhddevice.AudioMaxCompression = 0
softhddevice.AudioMaxNormalize = 0
softhddevice.AudioNormalize = 0
softhddevice.AudioPassthrough = 0
softhddevice.AudioSoftvol = 1
softhddevice.AudioStereoDescent = 0
softhddevice.AutoCrop.Delay = 0
softhddevice.AutoCrop.Interval = 0
softhddevice.AutoCrop.Tolerance = 0
softhddevice.Background = 0
softhddevice.BlackPicture = 0
softhddevice.Brightness = 0
softhddevice.ClearOnSwitch = 0
softhddevice.Contrast = 1000
softhddevice.DetachFromMainMenu = 0
softhddevice.HideMainMenuEntry = 0
softhddevice.Hue = 0
softhddevice.MakePrimary = 0
softhddevice.MaxSizeGPUImageCache = 128
softhddevice.Osd.Height = 0
softhddevice.Osd.Width = 0
softhddevice.pip.Alt.Height = 50
softhddevice.pip.Alt.VideoHeight = 50
softhddevice.pip.Alt.VideoWidth = 0
softhddevice.pip.Alt.VideoX = 0
softhddevice.pip.Alt.VideoY = 0
softhddevice.pip.Alt.Width = 0
softhddevice.pip.Alt.X = 0
softhddevice.pip.Alt.Y = 50
softhddevice.pip.Height = 18
softhddevice.pip.VideoHeight = 0
softhddevice.pip.VideoWidth = 0
softhddevice.pip.VideoX = 0
softhddevice.pip.VideoY = 0
softhddevice.pip.Width = 18
softhddevice.pip.X = 79
softhddevice.pip.Y = 78
softhddevice.Saturation = 1000
softhddevice.SkinToneEnhancement = 0
softhddevice.SoftStartSync = 0
softhddevice.StudioLevels = 0
softhddevice.Suspend.Close = 0
softhddevice.Suspend.X11 = 0
softhddevice.UHD.CutLeftRight = 0
softhddevice.UHD.CutTopBottom = 0
softhddevice.UHD.Deinterlace = 0
softhddevice.UHD.Denoise = 0
softhddevice.UHD.FirstField = 0
softhddevice.UHD.InverseTelecine = 0
softhddevice.UHD.Scaling = 0
softhddevice.UHD.SecondField = 0
softhddevice.UHD.Sharpen = 0
softhddevice.UHD.SkipChromaDeinterlace = 0
softhddevice.Video4to3DisplayFormat = 1
softhddevice.VideoOtherDisplayFormat = 1`

**Comment by fiveten59** [comment]
Don't get crazy y for it
Tomorrow I'll check if the problem is just a setup of tv and not the plug

**Comment by fiveten59** [comment]
As suspected it's just of setup of the new tv
After installing vdr system on a friend's pc connected to another tv it was all okay. 
Now I've to find where is the prob on my tv
I'm really sorry you lost your time for that

**Comment by ua0lnj** [comment]
Try latest git, disable screensaver in menu, and you can turn off tv manually an any time.
