### ISSUE TITLE
Screensaver

### ISSUE THREAD

**Issue by fiveten59** [ua0lnj/vdr-plugin-softhddevice#46]
Great job 
now it's okay (release 1.9.5)

P.S. What's libdvbcsa new? where is it? I know only the old libdvbsca by vlc
Thank for all

**Comment by ua0lnj** [comment]
This is TODO :)
I did it for normal compilation.
If someone makes a new library for icam, it will be enough just to rebuild the plugin.

**Comment by ua0lnj** [comment]
There is a libdvbcsa patch on the internet, but I not tested it.
