### ISSUE TITLE
No audio on channels using only AAC audio encoding

### ISSUE THREAD

**Issue by JTe-git** [ua0lnj/vdr-plugin-softhddevice#47]
There is no audio on channels using vdr-plugin-pvrinput with HDPVR and SPDIF audio input option. With this option audio encoding of the channel is AAC only (no AC3 is possible). 

This works with original the softhddevice plugin (0.6.1) and with the softhdcuvid (current) plugins.

**Comment by ua0lnj** [comment]
No audio in live mode only, or in playback too?
DVB channels with AAC works fine with me.
If playback have no sound too, upload the recording of some minutes please.

**Comment by JTe-git** [comment]
Also on playback. You can find a short recording at:
https://test-file

**Comment by ua0lnj** [comment]
Confirmed, no sound, I'll take a look.

**Comment by ua0lnj** [comment]
I tried to play your files.
No program plays sound and softhdcuvid doesn't play sound either. I tried mpv, vlc and ffmpeg. Are these the correct files?

**Comment by JTe-git** [comment]
That is strange. I will check up the recordings. My test scenario was following:
-I was not compiling the plugins but used the seahawk1986 ppa repository and tried on both Yammy and Focal installations with same results:
1) Install softhddevice / softhdddevic-cuvid -> no audio on those channels
2) remove softhdddevice install softhdcuvid -> audio on all channels

I did fix the nvidia drivers to 510 as 515 did not work with the cuvid versions

I recorded the sample under softhddevice, but I might have the permashift plugin on, so that might explain why there is no sound. I will try to make a new recording sample and I will also check there is sound with the recording.

**Comment by JTe-git** [comment]
Ok, I uploaded a new test file. I also tested the file and audio works with the old softhddevice (0.6.1), but not with the current version. Sorry about mess with the test files:
https://test-file

**Comment by ua0lnj** [comment]
Yes, mpv and softhdcuvid play sound, softhddevice no sound.

**Comment by ua0lnj** [comment]
Fixed, try latest version.

**Comment by JTe-git** [comment]
I tested the latest update. The results are:
1) Recording made with the old softhddevice plugin (0.6.1) -the one you used for testing: Ok, audio is now working
2) Live TV with the latest softhddevice plugin (1.9.6): No audio
3) Recording made with the latest softhddevice plugin (1.9.6) and trying playback with an old softhddevice plugin (0.6.1): No audio

So after the changes the audio works on old recordings, but there is no audio on live TV and neither audio on new recordings. With softhdcuvid there are no problems.

**Comment by ua0lnj** [comment]
Make recording with softhdcuvid, test and upload it, please.

**Comment by JTe-git** [comment]
I made a short recording with softhdcovid (3.7.3 on Jammy) with working audio:
https://test-file

**Comment by ua0lnj** [comment]
Play audio with softhddevice fine for me.
I don't know how else to reproduce the problem.
Enable CONFIG += -DDEBUG in Makefile, compile debug version and post all syslog with softhddevice in live TV.

**Comment by JTe-git** [comment]
I did a complete reinstall on my test server and now it works fine. There is audio on recordings and on live TV. I will close the issue. Thank you for finding a solution.
