### ISSUE TITLE
Clearing of subtitles is not ignored when a menu is open

### ISSUE THREAD

**Issue by JTe-git** [ua0lnj/vdr-plugin-softhddevice#48]
Problem: 
If DVB subtitles are on and a menu is opened, the menu is cleared when subtitles are cleared. 
The menu re-appears when a user is moving in the menu (the menu is redrawn), but the menu is again cleared when subtitles are cleared.

There is no problem with softhddevice plugin (0.6.1):
https://github.com/zillevdr/vdr-plugin-softhddevice-drm/commit/a920da652bc864a76f2064ddbbe323f3ab9d1add

**Comment by ua0lnj** [comment]
Yes, I saw this problem, but so far I have not done it.
But: https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/3d3a88e76c14a2c89169b83f241cff4d34158776
