### ISSUE TITLE
VDR draws subtitle without clearing the old

### ISSUE THREAD

**Issue by JTe-git** [ua0lnj/vdr-plugin-softhddevice#49]
This old bug has been reintroduced at some point. The problem description is:
-Some broadcasters send first two (2) lines of subtitles and then one (1) line subtitles without clearing the second line. The result is subtitles with one line of text from the previous subtitles and another line of text from the new subtitles. Also if a very long line is sent at first and then shorter line, the end of the old longer line is not always cleared.

Previously (in version  0.6.1) this has been solved by clearing the old subtitles before redrawing new, but somehow it has stopped working in some cases.

I can also record a sample if needed.

**Comment by ua0lnj** [comment]
Yes, please give me a sample.

**Comment by JTe-git** [comment]
The test file can be found at:
https://test-file

**Comment by ua0lnj** [comment]
Please check your record, there is a subtitle track, but subtitles are not displayed at all

**Comment by JTe-git** [comment]
There are two subtitle tracks with the recording. The subtitle pid 24 has no subtitles, but the 12 has the subtitles (or other way around). From info file:
X 3 24 fin SubtitleFih
X 3 12 fin SubtitleFin

**Comment by ua0lnj** [comment]
What settings should I set in VDR so that subtitles appear?

**Comment by JTe-git** [comment]
I select the subtitle track with the "Subtitles" remote key. If you do not have that defined you could define the key in the /etc/vdr/keymacros.conf, the line:
Yellow    Subtitles
Will setup your yellow remote key to be the subtitles key. After that you can change the subtitle track by pressing the yellow key on you remote.

**Comment by ua0lnj** [comment]
Yes, works.
