### ISSUE TITLE
undefined symbol: gltexturesubimage2d in test branch

### ISSUE THREAD

**Issue by rofehr** [ua0lnj/vdr-plugin-softhddevice#50]
in the 'test' branch I always get the error message
undefined symbol: gltexturesubimage2d.

**Comment by rofehr** [comment]
in the branch 'vdpau+vaapi+cuvid' there is no such problem.

**Comment by ua0lnj** [comment]
Do make in plugin's directory and post compilation log.

**Comment by rofehr** [comment]
here is the compilation log
[log.do_compile.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/10218218/log.do_compile.txt)

**Comment by ua0lnj** [comment]
Until I was able to reproduce such an error.
gltexturesubimage2d is contained in libGL and libOpenGL.
These libraries are linked when building, and it's not clear why vdr doesn't see them at startup.

**Comment by ua0lnj** [comment]
You can try run vdr with LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libGL.so" and set you path to libGL.so.

**Comment by rofehr** [comment]
I will give it a try

**Comment by MarkusEh** [comment]
I have the same error :( .
I use opengl-4.2  (ubuntu focal), and this function comes wit OpenGL 4.5 ...

**Comment by ua0lnj** [comment]
Fixed, https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/9141907d671fefc3fb0e42317740f0dc4d696f6f
