### ISSUE TITLE
Heavy pixelation on HDTV with Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by JTe-git** [ua0lnj/vdr-plugin-softhddevice#51]
The HDTV picture has heavy pixelation after channel change when running on Ubuntu 22.04 LTS (Jammy Jellyfish). The pixelation lasts about 1-2 seconds and then the TV picture is usually fine. Some channels like CNN on Astra 19.2. have a constant pixelation problem (continuing pretty much all the time).

There are no problems with the SDTV channels (neither satellite nor terrestrial).

There are no problems (neither with HDTV switching nor CNN) when using the vdr-plugin-softhdcuvid.

I can provide some log information or recordings if needed. (I guess only recording helping would be the CNN causing pixelation all the time).

**Comment by ua0lnj** [comment]
The softhdcuvid is made differently. I have a similar effect on scrambled channels, do you have it with all channels or on scrambled ones? And what video module are you using, va-api, vdpau, cuvid? There are no problems on non-encoded channels and cuvid video module for me. In any case, 1-2 seconds to switch does not really bother me. Most likely there will be nothing special in the logs, you can shoot a video on your phone and post it. I will compare with what I have.
I can't receive Astra, and the recording makes sense if you can reproduce the problem with it.
Also, try set reset decoder or black screen when channel change in plugin menu.

**Comment by JTe-git** [comment]
I am using cuvid -video module and the effect is on clear channels. I have it with all HD channels, but it is less disturbing on satellite channels than on the DVBT2 channels. The exception being the CNN, and some other satellite channels having the problem constantly (not only when switching).

Yes I have been trying the reset decoder and black screen without too much of help.

I will make some recordings.

**Comment by JTe-git** [comment]
You can now find a CNN test file with heavy pixelation on Ubuntu 22.04 LTS (Jammy Jellyfish) at:
https://en/test-file

The pixelation occurs basically every time there is a bigger change in image.

**Comment by ua0lnj** [comment]
No problem with you video for me, on 2 computers, with GT1030 both.
Make a full log, from loading vdr, maybe I'll find something. Until I can reproduce it.

**Comment by JTe-git** [comment]
Did you try with Ubuntu 22.04 LTS (Jammy Jellyfish)? I have no pixelation with other linux versions, only with Ubuntu 22.04. I will make a full log.

**Comment by ua0lnj** [comment]
Ubuntu 22.04 LTS, ffmpeg latest from source.
Fedora 37, ffmpeg 5.1.2.

**Comment by JTe-git** [comment]
And what is your Nvidia driver version? (I am trying to narrow down the problem)

**Comment by ua0lnj** [comment]
nvidia-driver-525-525.78.01-0ubuntu0.22.04.1

**Comment by JTe-git** [comment]
I did some extrensive testing and I have:
-Nvidia GT1030
-nvidia 525.78.01 (CUDA Version: 12.0)
-ffmpeg version 5.1.2-0ubuntu1~22.04.sav2
-Ubuntu 22.04.1 LTS

And the pixelation error is still there  when changing channels & on CNN all the time (happens also with the example video). When changing channels to a HD channel the log is usually like this:

Jan 26 18:31:32 vdr vdr: audio/alsa: using device 'default'
Jan 26 18:31:32 vdr vdr: audio/alsa: start delay 336ms
Jan 26 18:31:32 vdr vdr: video: get hwaccel context, not supported
Jan 26 18:31:33 vdr vdr: audio/alsa: avail underrun error? 'Broken pipe'
Jan 26 18:31:33 vdr vdr: video/vdpau: can't render mixer: An invalid handle value was provided.
Jan 26 18:31:35 vdr vdr: video/vdpau: synced after 117 frames

**Comment by ua0lnj** [comment]
This is a vdpau, not cuvid.
I tested cuvid only, will test vdpau today.

**Comment by ua0lnj** [comment]
Confirmed.
The problem is only with vdpau. Incorrect field order error. I will look this.
But with gt-1030 I use -v cuvid, than you can see 4k hevc video.

**Comment by ua0lnj** [comment]
Found solution. In makefile, disable CONFIG += -DUSE_MPEG_COMPLETE.
#CONFIG += -DUSE_MPEG_COMPLETE
And recompile the plugin.
Test all you channels, and I disable this in git as default.
