### ISSUE TITLE
[VAAPI] libva-2.17 breaks video output

### ISSUE THREAD

**Issue by tmn505** [ua0lnj/vdr-plugin-softhddevice#52]
This is to track upstream issue after DRI3 addition: https://github.com/intel/libva/issues/677
Symptoms are black screen without OSD only audio playing.

Example of log output before acquiring stream:
`vdr[3334]: video/vaapi: vaPutSurface failed -1`

and after acquiring stream:
`vdr[3334]: video/vaapi: vaPutSurface failed: unknown libva error`

**Comment by ua0lnj** [comment]
Try test branch and -v va-api-egl.
Need egl libs.

**Comment by tmn505** [comment]
Hi.
The test branch with `-v va-api-egl` works on both 2.16 and 2.17 libva versions.

I also tried `va-api-glx`, it outputs following error on libva 2.17:
`vdr[813]: video/glx: vaCopySurfaceGLX failed`

while on libva 2.16, the log looks normal but picture looks like this:
![va-api-glx](https://user-images.githubusercontent.com/1316161/216099258-b76c1c91-7d5f-480d-b93b-6b9b740d46a7.jpg)

**Comment by ua0lnj** [comment]
For latest driver you can use va-api-egl only. New driver not support subpicture for OSD, and vaCopySurfaceGLX not works with it.
Also look at readme, for va-api-glx use export allow_rgb10_configs=false.
The glx works slow on Intel, and UHD not usable.

**Comment by pbiering** [comment]
Got hit also after upgrading my test VDR to next to be released Fedora 38 containing also `libva-2.17`. Can confirm 'test' branch is working by local rebuild of `vdr-softhddevice` using release 1.10.0 and diff to 'test' branch.

**Comment by pbiering** [comment]
btw: regarding release number, was this intended to remove the "v" now on 1.10.0?

**Comment by ua0lnj** [comment]
This is a my mistake.

**Comment by pbiering** [comment]
@ua0lnj : any reason why 1.10.3 is still not containing EGL related extension from "test" branch? It's required here on Fedora 38 with libva-2.18.0-1 on a "Intel Broxton (Gen9) "

**Comment by pbiering** [comment]
@ua0lnj : can you at least rebase the "test" branch to 1.10.3?

**Comment by tmn505** [comment]
@pbiering as workaround link stable softhddevice from master branch to a static older libva library, that way it won't matter what distro provides.
There's PR pending in libva repository https://github.com/intel/libva/pull/716, does that fix the issue with master branch? If yes maybe pointing it to Fedora libva maintainer would solve the issue. I'll do my test later and post result here.

**Comment by ua0lnj** [comment]
I plan to merge the branches in version 2.0.0, but for this there are still some things that I still have to do that I do not have enough time for.

**Comment by pbiering** [comment]
> @pbiering as workaround link stable softhddevice from master branch to a static older libva library, that way it won't matter what distro provides. There's PR pending in libva repository [intel/libva#716](https://github.com/intel/libva/pull/716), does that fix the issue with master branch? If yes maybe pointing it to Fedora libva maintainer would solve the issue. I'll do my test later and post result here.

Thank you for pointing to the patch, which makes usable toggle visible:

`getenv("LIBVA_DRI3_DISABLE")`

Now using `export LIBVA_DRI3_DISABLE="1"` and all is fine with vanilla libva 2.18 and output `va-api`!

BTW: according to `intel_gpu_top`, `va-api` consumes approx. 50% for "Render/3D" while `va-api-egl` only approx. 25%

**Comment by tmn505** [comment]
Glad it helped. I my case (master+va-api+patched-libva) there is a picture for h264 or mpeg2 broadcasts but fails on hevc ones with log spamming:
```
video/vaapi: vaSyncSurface failed
video/vaapi: vaSyncSurface failed: operation failed
```
With whatever format OSD is not displayed at all and log shows:
`video/vaapi: can't find a supported subpicture format`

I still use test branch for the time being, works flawlessly.

My system is libva 2.18.0, ffmpeg 6.0 and kernel 6.1.
Output of vainfo:
```
vainfo: VA-API version: 1.19 (libva 2.18.2)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

**Comment by pbiering** [comment]
Mine looks a little bit different, OSD is working fine, DVB-C serves here no free-to-cable HVEC content, so can't test.

```
ffmpeg-6.0
libva-2.18.0
kernel-6.3.11
intel-media-driver-23.1.6
```

```
vainfo: VA-API version: 1.18 (libva 2.18.2)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 ()
vainfo: Supported profile and entrypoints
...
```

**Comment by ua0lnj** [comment]
Fedora 40. With LIBVA_DRI3_DISABLE=1 works va-api, va-api-glx, va-api-egl. Without works va-api-egl only. I think the topic can be closed.

**Comment by tmn505** [comment]
Although this one https://github.com/intel/libva/pull/727 is still open, I agree about closing this issue, since necessary setup is mentioned in documentation.
The missing OSD on va-api must have been an issue of Arch Linux in my set-up. @ua0lnj please post ldd output of the plugin on Your system, maybe there's something missing in linking phase on my system.

**Comment by ua0lnj** [comment]
root@ua0lnjhome:/usr/local/src/vdr-2.6.7-mod/PLUGINS/src/vdr-plugin-softhddevice# ldd libvdr-softhddevice.so 
	linux-vdso.so.1 (0x00007ffc3ebbc000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007f9e00111000)
	libvdpau.so.1 => /lib64/libvdpau.so.1 (0x00007f9e0010b000)
	libva-x11.so.2 => /lib64/libva-x11.so.2 (0x00007f9e00103000)
	libva.so.2 => /lib64/libva.so.2 (0x00007f9e000d2000)
	libva-glx.so.2 => /lib64/libva-glx.so.2 (0x00007f9e000ca000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f9dfdd8c000)
	libGLU.so.1 => /lib64/libGLU.so.1 (0x00007f9e00071000)
	libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00007f9dfdd67000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f9dfdd56000)
	libxcb-screensaver.so.0 => /lib64/libxcb-screensaver.so.0 (0x00007f9e0006b000)
	libxcb-dpms.so.0 => /lib64/libxcb-dpms.so.0 (0x00007f9dfdd51000)
	libswscale.so.7 => /lib64/libswscale.so.7 (0x00007f9dfdcc2000)
	libswresample.so.4 => /lib64/libswresample.so.4 (0x00007f9dfdca2000)
	libavfilter.so.9 => /lib64/libavfilter.so.9 (0x00007f9dfd800000)
	libGLEW.so.2.2 => /lib64/libGLEW.so.2.2 (0x00007f9dfd740000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f9dfd5fd000)
	libglut.so.3 => /lib64/libglut.so.3 (0x00007f9dfd54f000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f9dfd486000)
	libavcodec.so.60 => /lib64/libavcodec.so.60 (0x00007f9dfc200000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f9dfdc9b000)
	libxcb-icccm.so.4 => /lib64/libxcb-icccm.so.4 (0x00007f9dfdc94000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f9dfdc69000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007f9dfdc57000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9dfbe00000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9dfc11d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9dfdc28000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9dfbc13000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9e00239000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f9dfdc14000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f9dfd46f000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f9dfdc0c000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007f9dfdc03000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f9dfd43e000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f9dfc0a4000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f9dfd438000)
	libavutil.so.58 => /lib64/libavutil.so.58 (0x00007f9dfaa00000)
	libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007f9dfbbb4000)
	libpostproc.so.57 => /lib64/libpostproc.so.57 (0x00007f9dfc095000)
	libavformat.so.60 => /lib64/libavformat.so.60 (0x00007f9dfa600000)
	libbs2b.so.0 => /lib64/libbs2b.so.0 (0x00007f9dfd430000)
	liblilv-0.so.0 => /lib64/liblilv-0.so.0 (0x00007f9dfc079000)
	librubberband.so.2 => /lib64/librubberband.so.2 (0x00007f9dfbb5d000)
	libmysofa.so.1 => /lib64/libmysofa.so.1 (0x00007f9dfc068000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f9dfa8ea000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f9dfbb3e000)
	liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007f9dfa886000)
	libplacebo.so.338 => /lib64/libplacebo.so.338 (0x00007f9dfa4f5000)
	libvmaf.so.1 => /lib64/libvmaf.so.1 (0x00007f9dfa3f7000)
	libtesseract.so.5.3.4 => /lib64/libtesseract.so.5.3.4 (0x00007f9dfa000000)
	libass.so.9 => /lib64/libass.so.9 (0x00007f9dfbb04000)
	libvidstab.so.1.2 => /lib64/libvidstab.so.1.2 (0x00007f9dfbaee000)
	libzmq.so.5 => /lib64/libzmq.so.5 (0x00007f9dfa362000)
	libzimg.so.2 => /lib64/libzimg.so.2 (0x00007f9df9f3a000)
	libshaderc_shared.so.1 => /lib64/libshaderc_shared.so.1 (0x00007f9df9a00000)
	libOpenCL.so.1 => /lib64/libOpenCL.so.1 (0x00007f9dfa85c000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f9df9eea000)
	libvpl.so.2 => /lib64/libvpl.so.2 (0x00007f9df9e8f000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f9dfa34f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9dfa32e000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9dfa31a000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f9df9e55000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f9df9e47000)
	libvpx.so.9 => /lib64/libvpx.so.9 (0x00007f9df9600000)
	libwebpmux.so.3 => /lib64/libwebpmux.so.3 (0x00007f9df9e3b000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9df9e08000)
	libdav1d.so.7 => /lib64/libdav1d.so.7 (0x00007f9df9425000)
	libopencore-amrwb.so.0 => /lib64/libopencore-amrwb.so.0 (0x00007f9df9df1000)
	librsvg-2.so.2 => /lib64/librsvg-2.so.2 (0x00007f9df9000000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f9df9d93000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f9df8eb3000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f9df8d7e000)
	libzvbi.so.0 => /lib64/libzvbi.so.0 (0x00007f9df997e000)
	libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00007f9df9d86000)
	libaom.so.3 => /lib64/libaom.so.3 (0x00007f9df8800000)
	libjxl.so.0.8 => /lib64/libjxl.so.0.8 (0x00007f9df8400000)
	libcodec2.so.1.2 => /lib64/libcodec2.so.1.2 (0x00007f9df82b2000)
	libgsm.so.1 => /lib64/libgsm.so.1 (0x00007f9df9d77000)
	libilbc.so.3 => /lib64/libilbc.so.3 (0x00007f9df996a000)
	libjxl_threads.so.0.8 => /lib64/libjxl_threads.so.0.8 (0x00007f9df9d71000)
	libmp3lame.so.0 => /lib64/libmp3lame.so.0 (0x00007f9df823b000)
	libopencore-amrnb.so.0 => /lib64/libopencore-amrnb.so.0 (0x00007f9df9940000)
	libopenjp2.so.7 => /lib64/libopenjp2.so.7 (0x00007f9df81d2000)
	libopus.so.0 => /lib64/libopus.so.0 (0x00007f9df816a000)
	librav1e.so.0 => /lib64/librav1e.so.0 (0x00007f9df7e00000)
	libspeex.so.1 => /lib64/libspeex.so.1 (0x00007f9df9924000)
	libSvtAv1Enc.so.2 => /lib64/libSvtAv1Enc.so.2 (0x00007f9df7600000)
	libtheoraenc.so.1 => /lib64/libtheoraenc.so.1 (0x00007f9df93f9000)
	libtheoradec.so.1 => /lib64/libtheoradec.so.1 (0x00007f9df93e5000)
	libtwolame.so.0 => /lib64/libtwolame.so.0 (0x00007f9df8d57000)
	libvo-amrwbenc.so.0 => /lib64/libvo-amrwbenc.so.0 (0x00007f9df814b000)
	libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007f9df811c000)
	libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007f9df7d68000)
	libwebp.so.7 => /lib64/libwebp.so.7 (0x00007f9df7cf7000)
	libx264.so.164 => /lib64/libx264.so.164 (0x00007f9df7200000)
	libx265.so.209 => /lib64/libx265.so.209 (0x00007f9df6c00000)
	libxvidcore.so.4 => /lib64/libxvidcore.so.4 (0x00007f9df74f3000)
	libopenh264.so.7 => /lib64/libopenh264.so.7 (0x00007f9df70f0000)
	libva-drm.so.2 => /lib64/libva-drm.so.2 (0x00007f9df991f000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f9df6ace000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f9df7ca2000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f9df6973000)
	libmodplug.so.1 => /lib64/libmodplug.so.1 (0x00007f9df67e3000)
	libopenmpt.so.0 => /lib64/libopenmpt.so.0 (0x00007f9df65f9000)
	libvapoursynth-script.so.0 => /lib64/libvapoursynth-script.so.0 (0x00007f9df93de000)
	libchromaprint.so.1 => /lib64/libchromaprint.so.1 (0x00007f9df8d48000)
	libbluray.so.2 => /lib64/libbluray.so.2 (0x00007f9df7c4a000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007f9df6200000)
	libsrt.so.1.5 => /lib64/libsrt.so.1.5 (0x00007f9df650d000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f9df649c000)
	libsmbclient.so.0 => /lib64/libsmbclient.so.0 (0x00007f9df80f2000)
	libserd-0.so.0 => /lib64/libserd-0.so.0 (0x00007f9df74db000)
	libsord-0.so.0 => /lib64/libsord-0.so.0 (0x00007f9df7c40000)
	libsratom-0.so.0 => /lib64/libsratom-0.so.0 (0x00007f9df74d0000)
	libfftw3.so.3 => /lib64/libfftw3.so.3 (0x00007f9df5e00000)
	libsamplerate.so.0 => /lib64/libsamplerate.so.0 (0x00007f9df5c92000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f9df70d0000)
	libunwind.so.8 => /lib64/libunwind.so.8 (0x00007f9df6482000)
	libvulkan.so.1 => /lib64/libvulkan.so.1 (0x00007f9df6186000)
	libdovi.so.3 => /lib64/libdovi.so.3 (0x00007f9df6107000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f9df5bfe000)
	libleptonica.so.6 => /lib64/libleptonica.so.6 (0x00007f9df5800000)
	libsodium.so.26 => /lib64/libsodium.so.26 (0x00007f9df6422000)
	libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x00007f9df60be000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f9df5baa000)
	libSPIRV-Tools.so => /lib64/libSPIRV-Tools.so (0x00007f9df5696000)
	libSPIRV-Tools-opt.so => /lib64/libSPIRV-Tools-opt.so (0x00007f9df5400000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f9df5b87000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007f9df7c37000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f9df5b59000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f9df5232000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f9df5b48000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f9df5b2e000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f9df5ac5000)
	libffi.so.8 => /lib64/libffi.so.8 (0x00007f9df5686000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f9df5196000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f9df60b2000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f9df5676000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f9df74cb000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f9df50e7000)
	libhwy.so.1 => /lib64/libhwy.so.1 (0x00007f9df5ab8000)
	libbrotlienc.so.1 => /lib64/libbrotlienc.so.1 (0x00007f9df5047000)
	liblpcnetfreedv.so.0.5 => /lib64/liblpcnetfreedv.so.0.5 (0x00007f9df4000000)
	libogg.so.0 => /lib64/libogg.so.0 (0x00007f9df566c000)
	libsharpyuv.so.0 => /lib64/libsharpyuv.so.0 (0x00007f9df70c8000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f9df565e000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f9df5638000)
	libmvec.so.1 => /lib64/libmvec.so.1 (0x00007f9df4f4d000)
	libmpg123.so.0 => /lib64/libmpg123.so.0 (0x00007f9df4ef3000)
	libvorbisfile.so.3 => /lib64/libvorbisfile.so.3 (0x00007f9df562d000)
	libpython3.12.so.1.0 => /lib64/libpython3.12.so.1.0 (0x00007f9df3a00000)
	libudfread.so.0 => /lib64/libudfread.so.0 (0x00007f9df5623000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007f9df389d000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f9df4ed1000)
	libunistring.so.5 => /lib64/libunistring.so.5 (0x00007f9df36f0000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007f9df560d000)
	libnettle.so.8 => /lib64/libnettle.so.8 (0x00007f9df3697000)
	libhogweed.so.6 => /lib64/libhogweed.so.6 (0x00007f9df3655000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f9df35b1000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f9df3000000)
	libreplace-private-samba.so => /usr/lib64/samba/libreplace-private-samba.so (0x00007f9df3ffb000)
	libsamba-security-private-samba.so => /usr/lib64/samba/libsamba-security-private-samba.so (0x00007f9df3571000)
	libmsrpc3-private-samba.so => /usr/lib64/samba/libmsrpc3-private-samba.so (0x00007f9df3fcd000)
	liblibcli-lsa3-private-samba.so => /usr/lib64/samba/liblibcli-lsa3-private-samba.so (0x00007f9df356a000)
	libsmbconf.so.0 => /lib64/libsmbconf.so.0 (0x00007f9df34d6000)
	libndr.so.4 => /lib64/libndr.so.4 (0x00007f9df34b7000)
	liblibsmb-private-samba.so => /usr/lib64/samba/liblibsmb-private-samba.so (0x00007f9df2f99000)
	libsamba-util.so.0 => /lib64/libsamba-util.so.0 (0x00007f9df2f25000)
	libsamba-credentials.so.1 => /lib64/libsamba-credentials.so.1 (0x00007f9df2f0a000)
	libsamba-errors.so.1 => /lib64/libsamba-errors.so.1 (0x00007f9df2dea000)
	libsamba-hostconfig.so.0 => /lib64/libsamba-hostconfig.so.0 (0x00007f9df2dbb000)
	libndr-standard.so.0 => /lib64/libndr-standard.so.0 (0x00007f9df2a00000)
	libtevent-util.so.0 => /lib64/libtevent-util.so.0 (0x00007f9df34ae000)
	libgse-private-samba.so => /usr/lib64/samba/libgse-private-samba.so (0x00007f9df2d8c000)
	libdcerpc-samba-private-samba.so => /usr/lib64/samba/libdcerpc-samba-private-samba.so (0x00007f9df284a000)
	libsamba3-util-private-samba.so => /usr/lib64/samba/libsamba3-util-private-samba.so (0x00007f9df283e000)
	libsamba-debug-private-samba.so => /usr/lib64/samba/libsamba-debug-private-samba.so (0x00007f9df2832000)
	libcli-smb-common-private-samba.so => /usr/lib64/samba/libcli-smb-common-private-samba.so (0x00007f9df27ec000)
	libgenrand-private-samba.so => /usr/lib64/samba/libgenrand-private-samba.so (0x00007f9df27e6000)
	libsecrets3-private-samba.so => /usr/lib64/samba/libsecrets3-private-samba.so (0x00007f9df27d0000)
	libtevent.so.0 => /lib64/libtevent.so.0 (0x00007f9df27b8000)
	libtalloc.so.2 => /lib64/libtalloc.so.2 (0x00007f9df27aa000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f9df2780000)
	libssl.so.3 => /lib64/libssl.so.3 (0x00007f9df26ab000)
	libgif.so.7 => /lib64/libgif.so.7 (0x00007f9df269c000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f9df25ff000)
	libtiff.so.6 => /lib64/libtiff.so.6 (0x00007f9df2574000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f9df24ac000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f9df2495000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f9df248c000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f9df247c000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f9df2475000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f9df2463000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f9df245c000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f9df240a000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f9df23dd000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007f9df23d1000)
	libstable-sort-private-samba.so => /usr/lib64/samba/libstable-sort-private-samba.so (0x00007f9df23cc000)
	libndr-samba4-private-samba.so => /usr/lib64/samba/libndr-samba4-private-samba.so (0x00007f9df21cf000)
	libnpa-tstream-private-samba.so => /usr/lib64/samba/libnpa-tstream-private-samba.so (0x00007f9df21c4000)
	libcliauth-private-samba.so => /usr/lib64/samba/libcliauth-private-samba.so (0x00007f9df21ac000)
	libndr-samba-private-samba.so => /usr/lib64/samba/libndr-samba-private-samba.so (0x00007f9df2017000)
	libutil-tdb-private-samba.so => /usr/lib64/samba/libutil-tdb-private-samba.so (0x00007f9df2011000)
	libsamba-sockets-private-samba.so => /usr/lib64/samba/libsamba-sockets-private-samba.so (0x00007f9df1ff4000)
	libgensec-private-samba.so => /usr/lib64/samba/libgensec-private-samba.so (0x00007f9df1fc2000)
	libdcerpc-binding.so.0 => /lib64/libdcerpc-binding.so.0 (0x00007f9df1f9c000)
	libdbwrap-private-samba.so => /usr/lib64/samba/libdbwrap-private-samba.so (0x00007f9df1f8e000)
	libsocket-blocking-private-samba.so => /usr/lib64/samba/libsocket-blocking-private-samba.so (0x00007f9df1f8a000)
	libcommon-auth-private-samba.so => /usr/lib64/samba/libcommon-auth-private-samba.so (0x00007f9df1f76000)
	libsmbd-shim-private-samba.so => /usr/lib64/samba/libsmbd-shim-private-samba.so (0x00007f9df1f72000)
	libsamba-cluster-support-private-samba.so => /usr/lib64/samba/libsamba-cluster-support-private-samba.so (0x00007f9df1f5a000)
	libserver-id-db-private-samba.so => /usr/lib64/samba/libserver-id-db-private-samba.so (0x00007f9df1f54000)
	libtalloc-report-printf-private-samba.so => /usr/lib64/samba/libtalloc-report-printf-private-samba.so (0x00007f9df1f4f000)
	libutil-reg-private-samba.so => /usr/lib64/samba/libutil-reg-private-samba.so (0x00007f9df1f4a000)
	libinterfaces-private-samba.so => /usr/lib64/samba/libinterfaces-private-samba.so (0x00007f9df1f42000)
	libCHARSET3-private-samba.so => /usr/lib64/samba/libCHARSET3-private-samba.so (0x00007f9df1f3c000)
	libsys-rw-private-samba.so => /usr/lib64/samba/libsys-rw-private-samba.so (0x00007f9df1f37000)
	libmessages-dgm-private-samba.so => /usr/lib64/samba/libmessages-dgm-private-samba.so (0x00007f9df1f28000)
	libmessages-util-private-samba.so => /usr/lib64/samba/libmessages-util-private-samba.so (0x00007f9df1f24000)
	libtdb-wrap-private-samba.so => /usr/lib64/samba/libtdb-wrap-private-samba.so (0x00007f9df1f1d000)
	libserver-role-private-samba.so => /usr/lib64/samba/libserver-role-private-samba.so (0x00007f9df1f19000)
	libtime-basic-private-samba.so => /usr/lib64/samba/libtime-basic-private-samba.so (0x00007f9df1f15000)
	libutil-setid-private-samba.so => /usr/lib64/samba/libutil-setid-private-samba.so (0x00007f9df1f11000)
	libtdb.so.1 => /lib64/libtdb.so.1 (0x00007f9df1ef8000)
	libldap.so.2 => /lib64/libldap.so.2 (0x00007f9df1e93000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f9df1e84000)
	liblber.so.2 => /lib64/liblber.so.2 (0x00007f9df1e73000)
	libkrb5samba-private-samba.so => /usr/lib64/samba/libkrb5samba-private-samba.so (0x00007f9df1e63000)
	libsmb-transport-private-samba.so => /usr/lib64/samba/libsmb-transport-private-samba.so (0x00007f9df1e5b000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f9df1d6d000)
	libicui18n.so.74 => /lib64/libicui18n.so.74 (0x00007f9df1a00000)
	libicuuc.so.74 => /lib64/libicuuc.so.74 (0x00007f9df180c000)
	libauthkrb5-private-samba.so => /usr/lib64/samba/libauthkrb5-private-samba.so (0x00007f9df1d52000)
	libldbsamba-private-samba.so => /usr/lib64/samba/libldbsamba-private-samba.so (0x00007f9df17df000)
	libsamdb-common-private-samba.so => /usr/lib64/samba/libsamdb-common-private-samba.so (0x00007f9df17a9000)
	libldb.so.2 => /lib64/libldb.so.2 (0x00007f9df1772000)
	libndr-nbt.so.0 => /lib64/libndr-nbt.so.0 (0x00007f9df1746000)
	libcli-cldap-private-samba.so => /usr/lib64/samba/libcli-cldap-private-samba.so (0x00007f9df1d45000)
	libaddns-private-samba.so => /usr/lib64/samba/libaddns-private-samba.so (0x00007f9df1d34000)
	libcli-nbt-private-samba.so => /usr/lib64/samba/libcli-nbt-private-samba.so (0x00007f9df1739000)
	libiov-buf-private-samba.so => /usr/lib64/samba/libiov-buf-private-samba.so (0x00007f9df1735000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f9df1676000)
	libLerc.so.4 => /lib64/libLerc.so.4 (0x00007f9df15e7000)
	libjbig.so.2.1 => /lib64/libjbig.so.2.1 (0x00007f9df15d9000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f9df159d000)
	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007f9df1594000)
	libndr-krb5pac.so.0 => /lib64/libndr-krb5pac.so.0 (0x00007f9df1572000)
	libasn1util-private-samba.so => /usr/lib64/samba/libasn1util-private-samba.so (0x00007f9df1569000)
	libsamba-modules-private-samba.so => /usr/lib64/samba/libsamba-modules-private-samba.so (0x00007f9df1562000)
	libwbclient.so.0 => /lib64/libwbclient.so.0 (0x00007f9df154d000)
	libsamdb.so.0 => /lib64/libsamdb.so.0 (0x00007f9df152d000)
	libMESSAGING-SEND-private-samba.so => /usr/lib64/samba/libMESSAGING-SEND-private-samba.so (0x00007f9df1528000)
	libjansson.so.4 => /lib64/libjansson.so.4 (0x00007f9df1517000)
	libmsghdr-private-samba.so => /usr/lib64/samba/libmsghdr-private-samba.so (0x00007f9df1510000)
	libevent-2.1.so.7 => /lib64/libevent-2.1.so.7 (0x00007f9df14b9000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f9df149b000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f9df147a000)
	libicudata.so.74 => /lib64/libicudata.so.74 (0x00007f9def600000)
	libflag-mapping-private-samba.so => /usr/lib64/samba/libflag-mapping-private-samba.so (0x00007f9df1473000)
	libcli-ldap-common-private-samba.so => /usr/lib64/samba/libcli-ldap-common-private-samba.so (0x00007f9df1469000)
	libclidns-private-samba.so => /usr/lib64/samba/libclidns-private-samba.so (0x00007f9df1461000)
	libcluster-private-samba.so => /usr/lib64/samba/libcluster-private-samba.so (0x00007f9df145a000)
	libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f9df1422000)

**Comment by ua0lnj** [comment]
root@ua0lnjhome:/usr/local/src/vdr-2.6.7-mod# dnf list --installed|grep libva
libva.i686                                           2.21.0-3.fc40                       @fedora                         
libva.x86_64                                         2.21.0-3.fc40                       @fedora                         
libva-devel.x86_64                                   2.21.0-3.fc40                       @fedora                         
libva-intel-driver.x86_64                            2.4.1-14.20221130gitab755cb.fc40    @rpmfusion-free                 
libva-nvidia-driver.x86_64                           0.0.12-2.fc40                       @updates                        
libva-utils.x86_64                                   2.21.0-1.fc40                       @fedora
