### ISSUE TITLE
Segmentation fault with glibc 2.37 on Arch Linux

### ISSUE THREAD

**Issue by tmn505** [ua0lnj/vdr-plugin-softhddevice#53]
This started to happen after recent update. Vdr starts normally but after few moments (usually ~ 1min) it segfaults (without interaction). It doesn't trigger when channels are constantly switched, but after I settle on a channel it segfaults after few moments. Before glibc update the test branch worked well.

Gdb session output: [gdb-softhddevice-test-glibc-2.37.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/10676768/gdb-softhddevice-test-glibc-2.37.txt)

Core dump: [core.vdr.666.d39aed6931914bd1ad2fcff9d463bd98.458.1675781462000000.gz](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/10676777/core.vdr.666.d39aed6931914bd1ad2fcff9d463bd98.458.1675781462000000.gz)

**Comment by ua0lnj** [comment]
Try comment line 7587 in video.c
//VaapiMessage(0, NULL);

**Comment by tmn505** [comment]
Yep, that fixes the segfault.

**Comment by ua0lnj** [comment]
Ok, I'll fix this.

**Comment by ua0lnj** [comment]
Try git.

**Comment by tmn505** [comment]
That commit also fixed it, thanks. Closing.
