### ISSUE TITLE
Pixelation when changing HDTV channels on Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by JTe-git** [ua0lnj/vdr-plugin-softhddevice#54]
The softhddevice starts to work very well with Ubuntu 22.04 LTS (Jammy Jellyfish), but there is on more problem. When switching to a HDTV channels (vdpau used) quite heavy pixelation occurs for about 2-3 seconds. This does not happen with cuvid (-v cuvid). Also it does not happen when switching to a SD channel.

The pixelation looks very similar than with the  issue #51, so there might be incorrect field order when the picture and sound are synchronized (that is my wild guess)?

I can provide a video if needed.

**Comment by ua0lnj** [comment]
Yes, need recording. It seems that the problem requires a deeper study.
On all HDTV?

**Comment by JTe-git** [comment]
I made some tests with DEBUG enabled. The log looks like this when switching channels and having the pixelation:

https://logpaste.com/T5Og4B2V

I hope it helps.

**Comment by ua0lnj** [comment]
This problem is preserved if you cancel the commit for #51 ?
This is h264 1920x1080 vdpau, and seems, I seen this.
#51 fix mpeg2, but may be Maybe it hurt the h264.

**Comment by JTe-git** [comment]
No, the problem existed before #51 and is still there. However it only appears with Ubuntu 22.04 LTS, not with previous versions of Ubuntu. I can upload a short mobile phone video of the pixelation for reference.

**Comment by ua0lnj** [comment]
Test git now. I don't have decode_slice_header error now, maybe it helped you.

**Comment by JTe-git** [comment]
It is now better and some channels work fine. It seems HD channels that are slow to switch work fine (when switching time is more than one second there is never problem). The channels switching faster have maximum of one second of pixelation. But there are also some HD channels switching fast and having no problem.

I think the problem occurs when the picture and sound is synchronized just after switching. If the picture is moving in slow motion there is pixelation and when the normal speed is reached pixelation disappears. 

There are more problems with the T2 channels than with the S2. 

There are no problems with SD channels and the previous problems with the CNN are also over (#51).

**Comment by JTe-git** [comment]
I managed to find a way to show the pixelation. In addition to channel change it occurs when starting a recording of those problematic channels (as it seems to be related to video-audio sync). I have included a short recording and when I start to play the recording there is a brief pixelation. On channel change the pixelation lasts usually much longer, but at least you can now test it. You can download the test recording at:
https://test-file

**Comment by ua0lnj** [comment]
I tested your recording. Yes, it have pixelation. I tried, but, so far I can't fix this problem.
Also, mpv and vlc with vdpau decoder have this pixelation too, seems this is a ffmpeg troubles.

**Comment by MegaV0lt** [comment]
With **cuvid** i also have some pixelation. But much less than with vdpau.
Using a NVidia 1050Ti

**Comment by ua0lnj** [comment]
Сan this be reproduce while playing the recording?
What ffmpeg version?

**Comment by MegaV0lt** [comment]
I check when at home and provide a short sample

**Comment by MegaV0lt** [comment]
Here some infos:

```
CPU:
  Info: quad core model: Intel Core i5-3550 bits: 64 type: MCP arch: Ivy Bridge rev: 9 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 1798 high: 2003 min/max: 1600/3700 cores: 1: 1740 2: 1803 3: 2003 4: 1649
    bogomips: 26399
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] vendor: PNY driver: nvidia v: 470.182.03
    bus-ID: 01:00.0
  Display: server: X.org v: 1.21.1.4 driver: X: loaded: nvidia gpu: nvidia tty: 150x40
  Message: GL data unavailable in console. Try -G --display
```
`ffmpeg version 4.4.2-0ubuntu0.22.04.1`

Full inforrmation and 5 minutes sample:
https://www.dropbox.com/sh/7cjmme5exsfaldh/AADZ2LclecNTU-BuHRxmY2u4a?dl=0

**Comment by ua0lnj** [comment]
simple enter ffmpeg

ffmpeg version N-109820-g2c4dcbd66b Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --enable-shared --enable-gpl --enable-version3 --enable-nonfree --disable-x86asm --enable-libdavs2 --enable-gcrypt --enable-gnutls --enable-libuavs3d --enable-libx264
  libavutil      58.  0.100 / 58.  0.100
  libavcodec     60.  0.100 / 60.  0.100
  libavformat    60.  0.100 / 60.  0.100
  libavdevice    60.  0.100 / 60.  0.100
  libavfilter     9.  0.100 /  9.  0.100
  libswscale      7.  0.100 /  7.  0.100
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    57.  0.100 / 57.  0.100

**Comment by ua0lnj** [comment]
Looks like i will have to install the same ffmpeg, i have no problem playing the recording.

**Comment by MegaV0lt** [comment]
Make some jumps in the recording. 10secs forward and or backwards. Pixelation is minimal but noticable when jumping in a scene with more movement

Edit: Pixelation is much better than with vdpau. I may ask the packager to update ffmpeg

**Comment by ua0lnj** [comment]
With cuvid no pixelation, with vdpau is a pixelation.
I'll see what I can do, but it doesn't seem to get any better.

**Comment by MegaV0lt** [comment]
If it is ok with your ffmpeg i will request an update. Don't worry. Pixelation is not much and i can live with it

**Comment by ua0lnj** [comment]
I installed ffmpeg-4.4.2, no pixelation with cuvid.
So it's not clear why.
I'll try to do something with vdpau.

**Comment by ua0lnj** [comment]
Looks like I've found something, I'll test it over the weekend.

**Comment by ua0lnj** [comment]
For me work fine.
Test with ffmpeg 3.3.1, 4.4.2, and latest.

**Comment by MegaV0lt** [comment]
Still have little pixelation when jumping around (Key 1 or 3). But can live with it. I use `-v cuvid`

Edit: Also still pixelation with vdpau
