### ISSUE TITLE
[cuvid] audio out of sync after a while

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#56]
Using -v cuvid
Version 1.10.1

Audio gets out of sync after a while on Channels and recordings with HD 1080i 
Sample https://www.dropbox.com/s/bqkctj6c71rj5cf/Testvid.tar.xz?dl=1

Edit: Out tof sync also with -v vdpau

**Comment by ua0lnj** [comment]
When jumping back, it is not synchronized instantly, so far.
