### ISSUE TITLE
video.c - fehlt da ein "+ 1" beim vorletzten Patch?

### ISSUE THREAD

**Issue by davie2000** [ua0lnj/vdr-plugin-softhddevice#67]
![grafik](https://github.com/ua0lnj/vdr-plugin-softhddevice/assets/21957383/253c2951-d241-4cef-aeeb-60005292a4cf)

Falls nicht: sorry, for the noise!

lg
  davie2000

**Comment by ua0lnj** [comment]
Yes, this is a bug, will fix.

**Comment by ua0lnj** [comment]
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/bbf259e72c89f6a0b51cd41391f20bcd87cba99f
