### ISSUE TITLE
ABS is not always defined

### ISSUE THREAD

**Issue by j1rie** [ua0lnj/vdr-plugin-softhddevice#72]
video.c:12075:21: warning: implicit declaration of function ‘ABS’; did you mean ‘FFABS’? [-Wimplicit-function-declaration]
  if (!IsReplay() && ABS(diff/90) > 1000000) goto skip_sync; //static image??? radio plugin

**Comment by ua0lnj** [comment]
Yes, it defined in va-api module, I will fix this.

**Comment by ua0lnj** [comment]
Fixed https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/b83723296bcc22e1112460433c0f482b62c9e765
