### ISSUE TITLE
problem with 2.0.9

### ISSUE THREAD

**Issue by j1rie** [ua0lnj/vdr-plugin-softhddevice#73]
With the commit "[Fix according to latest ffmpeg (libavfilter). Version 2.0.9.](https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/a4cfb8e30d1268c110319188ec69e6a75c32f439)" vdr does not start.
"[Changes for stillpicture. Version 2.0.8.](https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/51f345348e84fad941b50f581fef9213f3505178)" is fine.

ffmpeg version 4.4.4 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 7 (SUSE Linux)
configuration: --enable-shared --enable-gpl --enable-postproc --enable-pthreads --enable-swscale --enable-libx264 --enable-avresample --enable-cuvid --enable-nonfree --extra-cflags=-I/usr/local/include/ffnvcodec/ --enable-cuda
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

**Comment by ua0lnj** [comment]
Error ?
I tested ffmpeg-4.4.4 and Ubuntu 22.04, all ok.

**Comment by j1rie** [comment]
I got a segfault.
I will check further.

**Comment by j1rie** [comment]
https://www.vdr-portal.de/forum/index.php?thread/136056-softhddevice-kernel-segfault/

**Comment by j1rie** [comment]
After deleting old ffmpeg libs everything is fine again.
Sorry for the noise.
