### ISSUE TITLE
syslog gets filled with warnings when DPMS = off

### ISSUE THREAD

**Issue by p-m** [ua0lnj/vdr-plugin-softhddevice#76]
Hi,
When the screen switches off (or just blank), VDR prints a lot of warnings to syslog.
My DPMS setting: softhddevice.EnableDPMS = 2
Options: -fwno-mpeg-hw-decoder
Please find attached the messages.
How could I avoid theses messages please?
TIA for any hints, Peter
[journal-vdr.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/15461521/journal-vdr.txt)

**Comment by rofehr** [comment]
witch nvidia do you use ?

**Comment by p-m** [comment]
> witch nvidia do you use ?

VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV730 PRO [Radeon HD 4650]

**Comment by ua0lnj** [comment]
Ok, see today.

**Comment by ua0lnj** [comment]
I haven't been able to reproduce it yet. Please enable debug in Mikefile:

CONFIG += -DDEBUG
CONFIG += -DOSD_DEBUG<><------># enable debug output+functions

rebuild and post the entire log from the start of VDR.

**Comment by ua0lnj** [comment]
I haven't been able to reproduce it yet. Please enable debug in Mikefile:

CONFIG += -DDEBUG
CONFIG += -DOSD_DEBUG<><------># enable debug output+functions

rebuild and post the entire log from the start of VDR.

**Comment by p-m** [comment]
Ok:
[journal-vdr-2.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/15467829/journal-vdr-2.txt)

At about 12:19:20: blank
At about 12:19:30: standby
At about 12:19:40: suspend
At about 12:19:50: off
At about 12:21:00: on again

**Comment by ua0lnj** [comment]
How is sound output, through the monitor? Does the sound disappear when the monitor is turned off?

**Comment by p-m** [comment]
Through the motherboard. When the monitor gets blank, the sound is interrupted about once per second.
I did not recognise it before, because I haven’t used the DPMS function yet in real life.

**Comment by ua0lnj** [comment]
If you turn off the DPMS and turn off the monitor with power, will the sound be interrupted?

**Comment by p-m** [comment]
No. Sound is normal. No log messages.

**Comment by ua0lnj** [comment]
Something is constantly sending a clear to the softhddevice, please check without the markad and remote plugins, I don’t use them.

And try disable watchdog - "setting watchdog timer to 60 seconds" in log.

**Comment by p-m** [comment]
Same result...

**Comment by ua0lnj** [comment]
I'll try to reproduce it again.

**Comment by ua0lnj** [comment]
Try disable hw decoder, -w no-hw-decoder. You can also try turning off the sound, -a noop. I think when the screen turns off something else stops working, either the video card or the sound. If we disable this right away, there should be no errors.

**Comment by p-m** [comment]
Ok. With -w no-hw-decoder and -a noop:
[journal-3.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/15486285/journal-3.txt)

And only with -w no-hw-decoder:
[journal-4.txt](https://github.com/ua0lnj/vdr-plugin-softhddevice/files/15486293/journal-4.txt)

**Comment by ua0lnj** [comment]
It seems I was able to reproduce it, I'll keep looking into it.
