### ISSUE TITLE
No video in one channel

### ISSUE THREAD

**Issue by jareguero** [ua0lnj/vdr-plugin-softhddevice#78]
There is no video in one tdt channel.
This is with AMD an vdpau.
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c3)
Log when changing to this channel:
[log.txt](https://github.com/user-attachments/files/16083147/log.txt)

Jose Alberto Reguero

**Comment by ua0lnj** [comment]
Nothing in the log...
If you record a video, will it show?
If you can reproduce the problem with the recording, post the recording.

**Comment by jareguero** [comment]
The record have the same problem. I attach some seconds.
[00001.zip](https://github.com/user-attachments/files/16098745/00001.zip)


Jose Alberto Reguero

**Comment by ua0lnj** [comment]
Yes, nvdec works, vdpau no. I'll look at this.
