### ISSUE TITLE
seem to be not right and orfand

### ISSUE THREAD

**Issue by 9000h** [ua0lnj/vdr-plugin-softhddevice#8]
https://github.com/ua0lnj/vdr-plugin-softhddevice/blob/bd7ab226cade7bc123ebfcd3c0c8c10508f3298a/codec.c#L96

**Comment by ua0lnj** [comment]
Not a significant error, maybe taken by the creator from another project, you can simply delete it.
Doesn't even create warnings when compiling.
Delete when I clean the code.
