### ISSUE TITLE
start in detach mode behaviour

### ISSUE THREAD

**Issue by geraldraaf** [ua0lnj/vdr-plugin-softhddevice#85]
Hi,
when i start vdr with satip-plugin and softhdddevice-plugin in detached mode vdr won't release tuner from minisatip until i attach then detach softhddevice.

My expected behaviour is that it isn't tuned in detached mode, but maybe i'am wrong.

1. When i start vdr with softhddevice in detached mode, it looks like the next picture.
![screenshot_1](https://github.com/user-attachments/assets/8ae39b04-bde1-421a-8aba-df1a50cf8652)

2. when i start vdr only with satip plugin it looks like the next picture and after a while it looks like in 3.
![screenshot_0](https://github.com/user-attachments/assets/0112a93e-34f7-475d-8fa6-6812a8e896d9)

3. status after some time with 2. or when i attach and detach softhddevice, so i think it's a problem with softhddevice.
![screenshot_2](https://github.com/user-attachments/assets/4f6f7f48-edfb-408c-8e9b-d6603cbfbaa9)

kind regards

**Comment by ua0lnj** [comment]
Did this work before?
What vdr version you use? Nothing has changed in the plugin as far as detach mode. But in vdr-2.6.9 there were changes with disconnecting tuners, I need to understand where to look. Perhaps it's worth writing about this on the vdr forum.

**Comment by geraldraaf** [comment]
I tested it with vdr 2.6.6, 2.6.7, 2.6.8 and 2.6.9 and in all versions the same behaviour. I will ask in the vdr forum and will close this issue.

**Comment by geraldraaf** [comment]
I start vdr satip softhddevice in softhddevice detach mode.
When i wake up vdr i send svdrpsend plug softhddevice atta and svdrpsend plug softhddevice deta.

I think start softhddevice with parameter -D is not the same as send DETA command.

**Comment by ua0lnj** [comment]
It's the same for softhddevice but not the same for vdr. Try change in plugin's osd settings "make primary device".

**Comment by geraldraaf** [comment]
no difference with "make primary device"

**Comment by ua0lnj** [comment]
Yes, there is a difference in the tuners operation when starting shd detached and when detach after start. But it is not yet clear whether it can be done differently.

**Comment by geraldraaf** [comment]
Here are some log files
**vdr start**
[vdr-start.log](https://github.com/user-attachments/files/16363576/vdr-start.log)

**svdrpsend plug softhddevice atta**
[vdr-atta.log](https://github.com/user-attachments/files/16363597/vdr-atta.log)

**svdrpsend plug softhddevice deta**
[vdr-deta.log](https://github.com/user-attachments/files/16363603/vdr-deta.log)

But i think we can close this issue because i found a solution for me.
With the computer i tested this behaviour, is my working Desktop machine, and sometimes i'am watching TV on this machine (when i wait backup compile etc).

I wasn't aware that the satip plugin has also a parameter to start in detach mode, so i start my computer including vdr with both plugins satip and softhddevice in detached mode, and my server is not woken up.

maybe you can mention this in your readme in the detache mode parameter.

Because i use gentoo i made a newer ebuild to install softhddevice in gentoo here it is
[vdr-softhddevice-9999.ebuild.txt](https://github.com/user-attachments/files/16363935/vdr-softhddevice-9999.ebuild.txt)
