### ISSUE TITLE
with last commit compile errors

### ISSUE THREAD

**Issue by j1rie** [ua0lnj/vdr-plugin-softhddevice#86]

**Comment by ua0lnj** [comment]
Give compile log pls.

**Comment by j1rie** [comment]
video.c: In function ‘VdpauRenderFrame’:
video.c:11301:42: error: ‘VDP_YCBCR_FORMAT_Y_U_V_444’ undeclared (first use in this function); did you mean ‘VDP_YCBCR_FORMAT_Y8U8V8A8’?
   VdpauVideoSurfacePutBitsYCbCr(surface, VDP_YCBCR_FORMAT_Y_U_V_444, data,
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                          VDP_YCBCR_FORMAT_Y8U8V8A8
video.c:11301:42: note: each undeclared identifier is reported only once for each function it appears in

and if instead of VdpauVideoSurfacePutBitsYCbCr I write VdpVideoSurfacePutBitsYCbCr I get another error

error: expected expression before

**Comment by ua0lnj** [comment]
I understand, the old version of libvdpau. Will fix.

**Comment by ua0lnj** [comment]
Please post the output of vdpauinfo.

**Comment by j1rie** [comment]
DISPLAY=:0 vdpauinfo
display: :0   screen: 0
API version: 1
Information string: NVIDIA VDPAU Driver Shared Library  550.100  Thu Jun 27 18:11:42 UTC 2024

Video surface:

name   width height types
-------------------------------------------
420     8192  8192  NV12 YV12
422     8192  8192  UYVY YUYV
444     8192  8192

Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4096  4096
MPEG2_SIMPLE                    3 65536  4096  4096
MPEG2_MAIN                      3 65536  4096  4096
H264_BASELINE                  51 65536  4096  4096
H264_MAIN                      51 65536  4096  4096
H264_HIGH                      51 65536  4096  4096
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      51 65536  4096  4096
H264_EXTENDED                  51 65536  4096  4096
H264_PROGRESSIVE_HIGH          51 65536  4096  4096
H264_CONSTRAINED_HIGH          51 65536  4096  4096
H264_HIGH_444_PREDICTIVE       51 65536  4096  4096
HEVC_MAIN                      153 262144  8192  8192
HEVC_MAIN_10                   153 262144  8192  8192
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   153 262144  8192  8192
HEVC_MAIN_444                  --- not supported ---

Output surface:

name              width height nat types
----------------------------------------------------
B8G8R8A8         32768 32768    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8
R10G10B10A2      32768 32768    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8

Bitmap surface:

name              width height
------------------------------
B8G8R8A8         32768 32768
R8G8B8A8         32768 32768
R10G10B10A2      32768 32768
B10G10R10A2      32768 32768
A8               32768 32768

Video mixer:

feature name                    sup
------------------------------------
DEINTERLACE_TEMPORAL             y
DEINTERLACE_TEMPORAL_SPATIAL     y
INVERSE_TELECINE                 y
NOISE_REDUCTION                  y
SHARPNESS                        y
LUMA_KEY                         y
HIGH QUALITY SCALING - L1        y
HIGH QUALITY SCALING - L2        -
HIGH QUALITY SCALING - L3        -
HIGH QUALITY SCALING - L4        -
HIGH QUALITY SCALING - L5        -
HIGH QUALITY SCALING - L6        -
HIGH QUALITY SCALING - L7        -
HIGH QUALITY SCALING - L8        -
HIGH QUALITY SCALING - L9        -

parameter name                  sup      min      max
-----------------------------------------------------
VIDEO_SURFACE_WIDTH              y         1     8192
VIDEO_SURFACE_HEIGHT             y         1     8192
CHROMA_TYPE                      y
LAYERS                           y         0        4

attribute name                  sup      min      max
-----------------------------------------------------
BACKGROUND_COLOR                 y
CSC_MATRIX                       y
NOISE_REDUCTION_LEVEL            y      0.00     1.00
SHARPNESS_LEVEL                  y     -1.00     1.00
LUMA_KEY_MIN_LUMA                y
LUMA_KEY_MAX_LUMA                y

**Comment by j1rie** [comment]
libvdpau is version 1.1.1

**Comment by ua0lnj** [comment]
please post:
cat /usr/include/vdpau/vdpau.h|grep VDP_YCBCR

**Comment by ua0lnj** [comment]
Fixed https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/8a93a7868d2834f3b352572ee735f17afc07d612
