### ISSUE TITLE
What does "video: get hwaccel context, not supported" mean

### ISSUE THREAD

**Issue by MegaV0lt** [ua0lnj/vdr-plugin-softhddevice#9]
I am getting this messages in the log:
`Mar  9 19:27:57 vdr01 vdr[4081]: video: get hwaccel context, not supported`

What does that mean? Everyting looks like it is working as expectet.

VDR 2.4.1
softhddevice (0.7.0-GIT3dac1fe) Video-Mode VDPAU
NVIDIA Driver Version: 340.107 
GFX: NVidia GT-630 (GK208)

**Comment by ua0lnj** [comment]
This is normal for vdpau, so it comes from the original code, the "get hwaccel context" function is not used with vdpau. While I did not touch this part of the code.

**Comment by MegaV0lt** [comment]
Ok, thank you for the explanation!
